---
- name: PlayBook
  hosts: server1
  become: true
  gather_facts: false
  tasks:

  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest

  - name: Install Docker Module for Python
    pip:
      name: docker
  
  - name: Pull Docker image Embedded
    docker_image:
      name: yourasoliar/embedded
      source: pull


  - name: Create containers
    community.docker.docker_container:
      name: embeddedcourse
      image: yourasoliar/embedded
      state: started
      auto_remove: true 
      ports:
      - "5000:5000"
      env:
        REDIS_HOST: 10.0.2.11
    with_sequence: count=1


    
