---
- name: PlayBook
  hosts: all
  become: true
  gather_facts: false
  tasks:

  - name: Embedded
    become: yes
    become_method: sudo
    docker_image:
      name: yourasoliar/embedded"
      source: pull

  - docker_container:
      name: yourasoliar/embedded"
      state: started

  ##### setup docker
  - name: install packages required by docker
    apt:
      update_cache: yes
      state: latest
      name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

  - name: add docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker apt repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: install docker
    apt:
      update_cache: yes
      state: latest
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  ##### setup ansible <---> docker

  - apt:
      update_cache: yes
      state: latest
      name: python3-pip

  - pip:
      name: docker

  ##### test
