---
- name: PlayBook
  hosts: balancer
  become: true
  gather_facts: false
  tasks:

  - name: Install Nginx
    apt: name=nginx state=latest update_cache=yes
    
  - name: Creating nginx config file
    copy:
      dest: "/etc/nginx/sites-enabled/default"
      content: |
          upstream embedded {
              server 10.0.2.4:5000;
          }

          server {
              listen 80;

              location / {
                  proxy_pass http://embedded;
              }
          }

  - name: Restart Nginx
    service: name=nginx state=restarted enabled=yes




    
